//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebService_Tekrar2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_NewVendorData", Namespace="http://schemas.datacontract.org/2004/07/WcfService_Tekrar2")]
    [System.SerializableAttribute()]
    public partial class tbl_NewVendorData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_AdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Musteri_SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Musteri_TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Musteri_Adi {
            get {
                return this.Musteri_AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_AdiField, value) != true)) {
                    this.Musteri_AdiField = value;
                    this.RaisePropertyChanged("Musteri_Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Musteri_Adresi {
            get {
                return this.Musteri_AdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_AdresiField, value) != true)) {
                    this.Musteri_AdresiField = value;
                    this.RaisePropertyChanged("Musteri_Adresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Musteri_Soyadi {
            get {
                return this.Musteri_SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.Musteri_SoyadiField, value) != true)) {
                    this.Musteri_SoyadiField = value;
                    this.RaisePropertyChanged("Musteri_Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Musteri_Telefon {
            get {
                return this.Musteri_TelefonField;
            }
            set {
                if ((this.Musteri_TelefonField.Equals(value) != true)) {
                    this.Musteri_TelefonField = value;
                    this.RaisePropertyChanged("Musteri_Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewVendorData", ReplyAction="http://tempuri.org/IService1/GetNewVendorDataResponse")]
        MvcWebService_Tekrar2.ServiceReference1.tbl_NewVendorData[] GetNewVendorData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNewVendorData", ReplyAction="http://tempuri.org/IService1/GetNewVendorDataResponse")]
        System.Threading.Tasks.Task<MvcWebService_Tekrar2.ServiceReference1.tbl_NewVendorData[]> GetNewVendorDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MvcWebService_Tekrar2.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MvcWebService_Tekrar2.ServiceReference1.IService1>, MvcWebService_Tekrar2.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcWebService_Tekrar2.ServiceReference1.tbl_NewVendorData[] GetNewVendorData() {
            return base.Channel.GetNewVendorData();
        }
        
        public System.Threading.Tasks.Task<MvcWebService_Tekrar2.ServiceReference1.tbl_NewVendorData[]> GetNewVendorDataAsync() {
            return base.Channel.GetNewVendorDataAsync();
        }
    }
}
