//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_Tekrar2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewVendorData
    {
        public string Musteri_Adi { get; set; }
        public string Musteri_Soyadi { get; set; }
        public string Musteri_Adresi { get; set; }
        public int Musteri_Telefon { get; set; }
    }
}
